SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
USE vo_manager;

ALTER TABLE voice_actors
  ADD COLUMN IF NOT EXISTS is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL COMMENT '进入回收站时间',
  ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(64) NULL COMMENT '删除操作者',
  ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本';

ALTER TABLE voice_roles
  ADD COLUMN IF NOT EXISTS is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL COMMENT '进入回收站时间',
  ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(64) NULL COMMENT '删除操作者',
  ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 1 COMMENT '乐观锁版本';
