-- Migration 2026-08-21: soft-delete + audit_log (MySQL 8.0 compatible)

ALTER TABLE voice_actors
  ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN revision INT NOT NULL DEFAULT 0,
  ADD COLUMN deleted_at DATETIME DEFAULT NULL,
  ADD COLUMN deleted_by VARCHAR(64) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor VARCHAR(64) NOT NULL DEFAULT '',
  action VARCHAR(32) NOT NULL DEFAULT '',
  table_name VARCHAR(64) NOT NULL DEFAULT '',
  record_id VARCHAR(64) NOT NULL DEFAULT '',
  detail_json JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
